import time
from pathlib import Path
from typing import List, Dict

class CookieManager:
    def __init__(self, cookie_file: Path):
        self.cookie_file = cookie_file
        self.cookie_file.parent.mkdir(parents=True, exist_ok=True)
        if not self.cookie_file.exists():
            self.cookie_file.touch()

    def update_cookies(self, new_cookies: List[Dict]):
        """
        Met à jour le fichier cookies.txt avec les nouveaux cookies reçus.
        Gère le format Netscape.
        """
        domain_map = {}
        
        # 1. On charge les cookies existants pour ne pas tout écraser
        if self.cookie_file.exists():
            with open(self.cookie_file, 'r') as f:
                for line in f:
                    if line.strip() and not line.startswith('#'):
                        parts = line.split('\t')
                        if len(parts) >= 7:
                            # Clé unique : domain + name
                            key = (parts[0], parts[5])
                            domain_map[key] = line

        # 2. On insère/écrase avec les nouveaux cookies
        for c in new_cookies:
            # Conversion format Chrome extension -> Netscape
            domain = c.get('domain', '')
            # Netscape format requires strict structure
            # domain, flag, path, secure, expiration, name, value
            
            # Gestion du flag (TRUE si le domaine commence par un point)
            flag = "TRUE" if domain.startswith('.') else "FALSE"
            path = c.get('path', '/')
            secure = "TRUE" if c.get('secure', False) else "FALSE"
            expiration = str(int(c.get('expirationDate', time.time() + 3600)))
            name = c.get('name', '')
            value = c.get('value', '')

            netscape_line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
            
            key = (domain, name)
            domain_map[key] = netscape_line

        # 3. On réécrit tout le fichier proprement
        with open(self.cookie_file, 'w') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by MediaFetcher Extension\n\n")
            for line in domain_map.values():
                f.write(line)